language: go

go:
    - "1.11.x"
python:
    - 3.7
env:
    global:
        - GO111MODULE=on
before_script:
    - go get ./...
    - go install
    - pip install --user cwltest
script:
    - ./testcases
