language: go

go:
    - 1.8
    - tip
python:
    - 3.6
before_script:
    - go get ./...
    - go install
    - pip install --user cwltest
script:
    - ./common-workflow-language/run_test.sh RUNNER=yacle -n1
