language: go

go:
    - 1.8
    - tip
python:
    - 3.6
before_script:
    - go get ./...
    - go install
    - pip install --user cwltest
script:
    - ./cwl/run_test.sh RUNNER=yacle -n1,2,3,4,5,7,8,9,10,11,12,54,86,90,86,108,111
